---
- name : настройка балансировщика
  hosts: balansir_frontend 
  # группа севреров
  become: yes 
  # говорим что все будет запускатся от имени root с наивысшими привилегиями
  
  #пишим переменные
  vars:
    source_file: ./site1/index.html
    source_file2: ./site2/index.html
    destin_file: /var/www/http/

  # Начинаем писать команды 

  tasks:
  - name: пингуем все сервера
    ping: 
    # модуль пинга

  - name: устанвоим mc
    dnf: name=mc state=latest

  - name: устанвоим  nginx
    dnf: name=nginx state=latest

  - name: запустим наш nginx и сделаем его запускаемой при старте севрера службой
    service: name=nginx state=started enabled=yes

    